version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gcp_demo
      POSTGRES_PASSWORD: "ybiaxV8KPbOEFilQASjuq5ok-xVZnlxr"
    volumes:
      - gcp_demo_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "6uq3Hx6QL8xKHiTwWzHWLEX0BxRKbvY_"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  gcp_demo_data:
